### ISSUE TITLE
Runtime error: FormatExeption was unhandled.

### ISSUE THREAD

**Issue by AllUsernamesHaveBeenTaken** [soshimozi/SimpleSoccer.Net#1]
When I try to run your solution I get the following error.

<img width="1071" alt="capture" src="https://cloud.githubusercontent.com/assets/10324377/26284213/4f3930f8-3e36-11e7-8dc5-a6b94abb2d7b.PNG">

Others can run it without any problems. Can you help me out?

**Comment by soshimozi** [comment]
Sure, it looks like you have a value that is not formatted correctly.  Can I see your Params.config file?

**Comment by AllUsernamesHaveBeenTaken** [comment]
It is the same as yours. I cloned your solution and tried to run it.

**Comment by soshimozi** [comment]
Okay, I wrote this code almost a decade ago and I haven't ran it in any modern IDE's probably since VS2008.  I will see what the problem is with a direct clone and run directly.

**Comment by soshimozi** [comment]
It runs fine for me in VS2015 - other than the bug where they get confused about what side they are on :D.  I haven't fixed that one yet.  Anyway, it doesn't crash for me.  So either you changed or Params.config file and put in some characters that are not a numeric value, or may you have some international settings which are causing the conversion to fail.  I'm not overriding the locale, so if your locale has a different numeric notation that could be causing an issue.  If you can show my your call stack that would be helpful.  You can do that by clicking on View Detail which will allow you to look at the exception itself which has the call stack information.  That will lead me back to where that call originated from.

**Comment by AllUsernamesHaveBeenTaken** [comment]
You were right. There were some issues in my Params.config. All fixed now.
And I have seen the players confusion :D Thanks for you support!
